### ISSUE TITLE
zero-shot setting for mmvax-stance

### ISSUE THREAD

**Issue by lsq945** [Supermaxman/gpt-gleam#2]
Hello, thank you very much for your work on multimodal stance detection. I would like to ask you a question. As far as I know, the training, validation and test sets of your mmvax-stance dataset contain all 113 frames. How can such a dataset be divided to conduct zero-shot experiments? This is equivalent to all frames have been seen, and there are no unknown targets.

**Comment by Supermaxman** [comment]
I believe you are referring to our "Tabula Rasa" zero-shot stance detection paper. We did not utilize any demonstrations from training or validation sets in that paper, therefore these 113 frames were truly unknown to the model at inference time.

Frame discovery and articulation, on the other hand, is a totally different task. We still prompted with the 113 frames knowing that each post had some relevance to that frame, but without knowing the stance. Identifying posts that evoke unknown frames is a field we study in our other publications.

If you are not referring to that work and are just curious how you could do cross-frame transfer learning (zero-shot stance detection across stance targets) you could still split the dataset up by frames. However, the splits would certainly be small.
